### ISSUE TITLE
Having issues baking the animation on FaceBuilder v2021.2.0

### ISSUE THREAD

**Issue by raghav96** [amilovsky/ktfacerig#1]
I have managed to generate the rig and perform the skinning for the FaceBuilder model I am working with, but I am unable to bake the animation in the current version of FaceBuilder. I have the animation loaded through a CSV file into the FaceBuilder plugin. Was wondering what version of FaceBuilder that this plugin works for, or if there are any particular issues with the code working for the current version of FaceBuilder.

**Comment by amilovsky** [comment]
Added support for three different model topologies. Now the addon will work with versions up to 2021.4.0
